"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-08-14 17:44:33.078755
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('external_auth_id', sa.String(length=128), nullable=False),
    sa.Column('auth_provider', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('theme', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'DELETED', name='userstatus', native_enum=False, length=16), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('external_auth_id', name=op.f('uq_users_external_auth_id'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=False)

    op.create_table('audit_logs',
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('actor_type', sa.String(length=24), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=48), nullable=True),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('family_id', sa.Uuid(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index('ix_audit_logs_family_occurred', ['family_id', 'occurred_at'], unique=False)

    op.create_table('families',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='familystatus', native_enum=False, length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_families_created_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_families'))
    )
    op.create_table('family_invitations',
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('invited_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'FAMILY', 'CAREGIVER', 'DOCTOR', 'VIEWER', name='membershiprole', native_enum=False, length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('invited_email', sa.String(length=320), nullable=True),
    sa.Column('invited_phone', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REVOKED', 'EXPIRED', name='invitationstatus', native_enum=False, length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['accepted_by_user_id'], ['users.id'], name=op.f('fk_family_invitations_accepted_by_user_id_users')),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], name=op.f('fk_family_invitations_family_id_families'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], name=op.f('fk_family_invitations_invited_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_family_invitations')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_family_invitations_token_hash'))
    )
    with op.batch_alter_table('family_invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_family_invitations_family_id'), ['family_id'], unique=False)

    op.create_table('family_memberships',
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'FAMILY', 'CAREGIVER', 'DOCTOR', 'VIEWER', name='membershiprole', native_enum=False, length=16), nullable=False),
    sa.Column('status', sa.Enum('INVITED', 'ACTIVE', 'SUSPENDED', 'REVOKED', name='membershipstatus', native_enum=False, length=16), nullable=False),
    sa.Column('invited_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], name=op.f('fk_family_memberships_family_id_families'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], name=op.f('fk_family_memberships_invited_by_user_id_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_family_memberships_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_family_memberships'))
    )
    with op.batch_alter_table('family_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_family_memberships_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_family_memberships_user_id'), ['user_id'], unique=False)
        batch_op.create_index('uq_family_memberships_family_user_live', ['family_id', 'user_id'], unique=True, sqlite_where=sa.text("status <> 'revoked'"), postgresql_where=sa.text("status <> 'revoked'"))

    op.create_table('senior_profiles',
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('preferred_name', sa.String(length=120), nullable=False),
    sa.Column('relationship_label', sa.String(length=64), nullable=True),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('blood_group', sa.String(length=8), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('allergies', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('consent_status', sa.Enum('NOT_REQUESTED', 'PENDING', 'GRANTED', 'ASSISTED', 'WITHDRAWN', name='consentstatus', native_enum=False, length=24), nullable=False),
    sa.Column('consent_recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consent_recorded_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['consent_recorded_by_user_id'], ['users.id'], name=op.f('fk_senior_profiles_consent_recorded_by_user_id_users')),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], name=op.f('fk_senior_profiles_family_id_families'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_senior_profiles_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_senior_profiles'))
    )
    with op.batch_alter_table('senior_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_senior_profiles_family_id'), ['family_id'], unique=False)

    op.create_table('appointments',
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('senior_profile_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('clinician', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'COMPLETED', 'CANCELLED', name='appointmentstatus', native_enum=False, length=16), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_appointments_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], name=op.f('fk_appointments_family_id_families'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['senior_profile_id'], ['senior_profiles.id'], name=op.f('fk_appointments_senior_profile_id_senior_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointments'))
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointments_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_senior_profile_id'), ['senior_profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_starts_at'), ['starts_at'], unique=False)

    op.create_table('emergency_contacts',
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('senior_profile_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('relationship_label', sa.String(length=64), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('consent_confirmed', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], name=op.f('fk_emergency_contacts_family_id_families'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['senior_profile_id'], ['senior_profiles.id'], name=op.f('fk_emergency_contacts_senior_profile_id_senior_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emergency_contacts'))
    )
    with op.batch_alter_table('emergency_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emergency_contacts_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_emergency_contacts_senior_profile_id'), ['senior_profile_id'], unique=False)

    op.create_table('family_notes',
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('senior_profile_id', sa.Uuid(), nullable=True),
    sa.Column('category', sa.Enum('NOTE', 'OBSERVATION', 'SUPPORT', 'CARE_PLAN', name='notecategory', native_enum=False, length=24), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], name=op.f('fk_family_notes_author_user_id_users')),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], name=op.f('fk_family_notes_family_id_families'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['senior_profile_id'], ['senior_profiles.id'], name=op.f('fk_family_notes_senior_profile_id_senior_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_family_notes'))
    )
    with op.batch_alter_table('family_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_family_notes_family_id'), ['family_id'], unique=False)

    op.create_table('health_readings',
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('senior_profile_id', sa.Uuid(), nullable=False),
    sa.Column('metric', sa.Enum('HEART_RATE', 'BLOOD_PRESSURE_SYSTOLIC', 'BLOOD_PRESSURE_DIASTOLIC', 'OXYGEN_SATURATION', 'BLOOD_GLUCOSE', 'BODY_TEMPERATURE', 'WEIGHT', 'STEPS', 'SLEEP_DURATION', name='healthmetric', native_enum=False, length=32), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=24), nullable=False),
    sa.Column('source', sa.Enum('MANUAL_SENIOR', 'MANUAL_FAMILY', 'DEVICE', 'CLINICIAN', 'IMPORT', name='healthsource', native_enum=False, length=24), nullable=False),
    sa.Column('source_device', sa.String(length=120), nullable=True),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], name=op.f('fk_health_readings_family_id_families'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], name=op.f('fk_health_readings_recorded_by_user_id_users')),
    sa.ForeignKeyConstraint(['senior_profile_id'], ['senior_profiles.id'], name=op.f('fk_health_readings_senior_profile_id_senior_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_health_readings'))
    )
    with op.batch_alter_table('health_readings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_health_readings_family_id'), ['family_id'], unique=False)
        batch_op.create_index('ix_health_readings_senior_metric', ['senior_profile_id', 'metric'], unique=False)

    op.create_table('medications',
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('senior_profile_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('form', sa.String(length=64), nullable=True),
    sa.Column('strength', sa.String(length=64), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('prescriber', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'ARCHIVED', name='medicationstatus', native_enum=False, length=16), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_medications_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], name=op.f('fk_medications_family_id_families'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['senior_profile_id'], ['senior_profiles.id'], name=op.f('fk_medications_senior_profile_id_senior_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_medications_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medications'))
    )
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medications_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medications_senior_profile_id'), ['senior_profile_id'], unique=False)

    op.create_table('notification_deliveries',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=True),
    sa.Column('senior_profile_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.Enum('MEDICATION_REMINDER', 'MISSED_DOSE', 'REMINDER', 'SOS', 'FAMILY_UPDATE', 'SYSTEM', name='notificationtype', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('related_entity_type', sa.String(length=48), nullable=True),
    sa.Column('related_entity_id', sa.Uuid(), nullable=True),
    sa.Column('dedupe_key', sa.String(length=160), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'SENT', 'OPENED', 'FAILED', 'CANCELLED', name='notificationstatus', native_enum=False, length=16), nullable=False),
    sa.Column('provider_reference', sa.String(length=200), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_error_code', sa.String(length=64), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], name=op.f('fk_notification_deliveries_family_id_families'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['senior_profile_id'], ['senior_profiles.id'], name=op.f('fk_notification_deliveries_senior_profile_id_senior_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notification_deliveries_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_deliveries')),
    sa.UniqueConstraint('dedupe_key', name=op.f('uq_notification_deliveries_dedupe_key'))
    )
    with op.batch_alter_table('notification_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_deliveries_user_id'), ['user_id'], unique=False)

    op.create_table('reminders',
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('senior_profile_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('MEDICATION', 'APPOINTMENT', 'ACTIVITY', 'HYDRATION', 'MEAL', 'OTHER', name='remindertype', native_enum=False, length=16), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('days_of_week', sa.String(length=32), nullable=False),
    sa.Column('local_time', sa.String(length=5), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'COMPLETED', 'ARCHIVED', name='reminderstatus', native_enum=False, length=16), nullable=False),
    sa.Column('last_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_reminders_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], name=op.f('fk_reminders_family_id_families'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['senior_profile_id'], ['senior_profiles.id'], name=op.f('fk_reminders_senior_profile_id_senior_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reminders'))
    )
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reminders_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminders_senior_profile_id'), ['senior_profile_id'], unique=False)

    op.create_table('timeline_events',
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('senior_profile_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('MEDICATION_TAKEN', 'MEDICATION_SKIPPED', 'MEDICATION_MISSED', 'MEDICATION_ADDED', 'REMINDER_COMPLETED', 'HEALTH_READING_ADDED', 'APPOINTMENT_SCHEDULED', 'SOS_TRIGGERED', 'MEMBER_JOINED', 'NOTE_ADDED', name='timelineeventtype', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('related_entity_type', sa.String(length=48), nullable=True),
    sa.Column('related_entity_id', sa.Uuid(), nullable=True),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_timeline_events_actor_user_id_users')),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], name=op.f('fk_timeline_events_family_id_families'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['senior_profile_id'], ['senior_profiles.id'], name=op.f('fk_timeline_events_senior_profile_id_senior_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timeline_events'))
    )
    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timeline_events_family_id'), ['family_id'], unique=False)
        batch_op.create_index('ix_timeline_events_senior_occurred', ['senior_profile_id', 'occurred_at'], unique=False)

    op.create_table('medication_schedules',
    sa.Column('medication_id', sa.Uuid(), nullable=False),
    sa.Column('days_of_week', sa.String(length=32), nullable=False),
    sa.Column('local_time', sa.String(length=5), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('dose_quantity', sa.String(length=64), nullable=True),
    sa.Column('dose_instructions', sa.Text(), nullable=True),
    sa.Column('late_after_minutes', sa.Integer(), nullable=False),
    sa.Column('missed_after_minutes', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'ENDED', name='schedulestatus', native_enum=False, length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], name=op.f('fk_medication_schedules_medication_id_medications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medication_schedules'))
    )
    with op.batch_alter_table('medication_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medication_schedules_medication_id'), ['medication_id'], unique=False)

    op.create_table('dose_events',
    sa.Column('medication_schedule_id', sa.Uuid(), nullable=False),
    sa.Column('medication_id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('senior_profile_id', sa.Uuid(), nullable=False),
    sa.Column('scheduled_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_local_time', sa.String(length=5), nullable=False),
    sa.Column('scheduled_timezone', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('DUE', 'REMINDED', 'TAKEN', 'SKIPPED', 'LATE', 'MISSED', 'CANCELLED', name='dosestatus', native_enum=False, length=16), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.Enum('PARENT_APP', 'FAMILY_APP', 'BACKEND_RULE', 'IMPORT', name='dosesource', native_enum=False, length=16), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], name=op.f('fk_dose_events_family_id_families'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], name=op.f('fk_dose_events_medication_id_medications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['medication_schedule_id'], ['medication_schedules.id'], name=op.f('fk_dose_events_medication_schedule_id_medication_schedules'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], name=op.f('fk_dose_events_recorded_by_user_id_users')),
    sa.ForeignKeyConstraint(['senior_profile_id'], ['senior_profiles.id'], name=op.f('fk_dose_events_senior_profile_id_senior_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dose_events')),
    sa.UniqueConstraint('medication_schedule_id', 'scheduled_at_utc', name='uq_dose_events_schedule_occurrence')
    )
    with op.batch_alter_table('dose_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dose_events_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dose_events_medication_id'), ['medication_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dose_events_medication_schedule_id'), ['medication_schedule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dose_events_scheduled_at_utc'), ['scheduled_at_utc'], unique=False)
        batch_op.create_index(batch_op.f('ix_dose_events_senior_profile_id'), ['senior_profile_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dose_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dose_events_senior_profile_id'))
        batch_op.drop_index(batch_op.f('ix_dose_events_scheduled_at_utc'))
        batch_op.drop_index(batch_op.f('ix_dose_events_medication_schedule_id'))
        batch_op.drop_index(batch_op.f('ix_dose_events_medication_id'))
        batch_op.drop_index(batch_op.f('ix_dose_events_family_id'))

    op.drop_table('dose_events')
    with op.batch_alter_table('medication_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medication_schedules_medication_id'))

    op.drop_table('medication_schedules')
    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.drop_index('ix_timeline_events_senior_occurred')
        batch_op.drop_index(batch_op.f('ix_timeline_events_family_id'))

    op.drop_table('timeline_events')
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reminders_senior_profile_id'))
        batch_op.drop_index(batch_op.f('ix_reminders_family_id'))

    op.drop_table('reminders')
    with op.batch_alter_table('notification_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_deliveries_user_id'))

    op.drop_table('notification_deliveries')
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medications_senior_profile_id'))
        batch_op.drop_index(batch_op.f('ix_medications_family_id'))

    op.drop_table('medications')
    with op.batch_alter_table('health_readings', schema=None) as batch_op:
        batch_op.drop_index('ix_health_readings_senior_metric')
        batch_op.drop_index(batch_op.f('ix_health_readings_family_id'))

    op.drop_table('health_readings')
    with op.batch_alter_table('family_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_family_notes_family_id'))

    op.drop_table('family_notes')
    with op.batch_alter_table('emergency_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emergency_contacts_senior_profile_id'))
        batch_op.drop_index(batch_op.f('ix_emergency_contacts_family_id'))

    op.drop_table('emergency_contacts')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_starts_at'))
        batch_op.drop_index(batch_op.f('ix_appointments_senior_profile_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_family_id'))

    op.drop_table('appointments')
    with op.batch_alter_table('senior_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_senior_profiles_family_id'))

    op.drop_table('senior_profiles')
    with op.batch_alter_table('family_memberships', schema=None) as batch_op:
        batch_op.drop_index('uq_family_memberships_family_user_live', sqlite_where=sa.text("status <> 'revoked'"), postgresql_where=sa.text("status <> 'revoked'"))
        batch_op.drop_index(batch_op.f('ix_family_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_family_memberships_family_id'))

    op.drop_table('family_memberships')
    with op.batch_alter_table('family_invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_family_invitations_family_id'))

    op.drop_table('family_invitations')
    op.drop_table('families')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_family_occurred')
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_phone'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
